[collector]
total_workers = 100
latency = 3500
fetch_public = false
path = "/home/suyash/proxy.txt"

[dns]
host = "127.0.0.1"
port = 9002
max_parallel_dns_lookups = 100
cache_cleanup_interval_secs = 30
cache_refresh_secs = 5
min_prest_hits = 25
cache_saturation = false
prewarm_domains = [
    "google.com",
    "chatgpt.com",
    "youtube.com",
    "github.com",
    "ping.archlinux.org",
    "www.discord.com",
    "go-updater.brave.com",
    "mobile.events.data.microsoft.com",
    "main.vscode-cdn.net",
    "cdn.discordapp.com",
]

[proxy]
host = "127.0.0.1"
port = 9003

[rotation]
rotate_sec = 60

[tproxy]
host = "127.0.0.1"
port = 9001
